env:
  global:
  - PATH: "/usr/local/texlive/bin/x86_64-linux:$PATH"
  - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
  - TARGET_BRANCH: gh-pages
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_373c076bae3a_key -iv $encrypted_373c076bae3a_iv -in bot_deploy_key.enc -out deploy_key -d
- git submodule update --init --recursive
script:
- sudo -E make tex_env
- make all
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then bash ./developers/deploy-ghpages.sh;
  fi
