env:
  global:
  - PATH: "/usr/local/texlive/bin/x86_64-linux:$PATH"
  - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
  - TARGET_BRANCH: gh-pages
  - secure: UhFnFXVvDwY+xJw6cA5gzCcO1gBAjNb/B2YeysOXxOHcCRTSlCS16/768fYjeMmamAM9OTlmuKPFkEne7ylifvquB/jun8OkYl0YXHtEBYB3lq7I3/kyLyJFsCG077aiCz0ZKdVq4Ae0j+LcBM6TRrQf05RA6Sm4L6Tlcb/I/gNshtthY+/7RYWnmkE63ab6FsWgDGDT4CoqI6MpjsISgAvAhAqcqgr8cLaQesqpa+sCQz6BO0t3ZBz2CURQ/gZapHlie+P9wPV5kXyEhXUyqSEgLX4XhOk705ljEwch+qcZgjW5OvnYFGHYJ7HyfMe7L5MnD3uWs8c9B39qC09vctJi/t/D+/ipFwVeV7Ai2fCP9wARmv8TwK2HZA1tcGMkE2BNHCRyE/mXa08a4atvYDl/u/cL3TyLJ76CVIiCu44+Qlr3XT9ne/jNbElqzv1CdxzjgXeQhbEY+wJvXx998yxlcAJpOyD75r91JIRAWmD0sRQKL1KF1/YKe05RE3rZT5S4gPdz5Nk7NAwUqSNYKmHUt/joD+7EmqPYTMDmX4Pa3P1RKU3Ds/ZHgKvAxxbDlIRJugEmL5UkbQW0pieeGcP54v8SO0JXVgV5GxHFY2S9mFdGyHJjoNZr9fUcI8pl6qCHqyxsQ5Es4kLKebt2FY+1BYsbUxYOMAidByj6Wks=
  - secure: zvp+fazWxRLH2dm3FSwYZG3Yutom0x5ISMkUsOq6lotq21UlsvcvEJJwTOvjJdzX9DutP6FJiswCV69/WvsDtC2XynwK1nMh51Bu6OolOHagHvTpV2D9x6uAWh+bWDFqVIjhwqrUX744zy5yPGv2+xNK8gdN7wvE5IuPUHtR3loz5UmUWy9D1VmBHuh5Vzn7rBaCV2fXPfvlnThhAOQ17j5zt9oaDUfH5AP2HkaSqQIKrSgqDOWumQqa3oUC8ZeqCt6/LrTuE4Zd0Znuji/kTOPXPNUB5Ba1cOswj+nXu5dVeupfSkkwI9fNhZ5phBrvm/S0ox9NK/hURTqOLgpurJOyMP26Hc2XTnA51Bf5f9+e1FCXViascpwMV8+B2mjSc4oU4tyqWskBZ2rL9Hk2GFVvtmWIkhL3GtiTXp7m6yRZl3WwMbjD0Rtn3x+5FKcJVEsc2kKfTbxNlNhjXhKaFUL4uXL60VzAUoHLlT2V6O5Km/4X2osqNAYdgn8YKkQh723T1ALudGATKcPzk1qgv0M9dpwRQykaplDIPzW7jC0ShQWoftDcI2rLEjqqeNlE7dA74S9GaYNCL/sirZOQgV/OX9iwL7tRoUg5nLGDjwTWkk5GtHD0n3BPskjU1tU3Xi26kQfA5gfXc+eqFP7OSoM/pCNZ8+i0nKw8Yj1PoPs=
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_373c076bae3a_key -iv $encrypted_373c076bae3a_iv -in bot_deploy_key.enc -out deploy_key -d
- git submodule update --init --recursive
script:
- sudo -E make tex_env
- make all
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then bash ./developers/deploy-ghpages.sh;
  fi
