env:
  global:
    - PATH: /usr/local/texlive/bin/x86_64-linux:$PATH
    - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
    - secure: "J/oFevIbuIyl1P16qdSVaNeJ0P1rL5Hub92SlDcNmhZ6NGu7+9N43fDs+uf3ihCmu664wZDKzB8YACetOfZ+XrZ9M72IfI3CzA7OWrx8elsub+WvaaOeVp3D+tDgNzxhXVRVJl5jZMmgEh5KjZ6GNshuTEPrIN+14s8bR4CciEM="
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
#before_script:
#  - cd ./developers/ && sudo -E ./texlive_install.sh && cd ../
script:
  - sudo -E make tex_env
  - make all
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "travis-ci"
  - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@${GH_REF} gh-pages > /dev/null
  - cd gh-pages
  - rm -f pdfs-latest/*.pdf
  - cp -Rf ../*.pdf ./pdfs-latest
  - git add -f .
  - git commit -m "Lastest PDFs on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to gh-pages"
  - git push -fq https://steveped:$GITHUB_API_KEY@github.com/UofABioinformaticsHub/Intro-Bash_2016_03_24-gh-pages gh-pages > /dev/null
#after_success:
#  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then bash ./developers/deploy-ghpages.sh; fi
