env:
  global:
  - PATH: "/usr/local/texlive/bin/x86_64-linux:$PATH"
  - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
  - TARGET_BRANCH: gh-pages
  - secure: UhFnFXVvDwY+xJw6cA5gzCcO1gBAjNb/B2YeysOXxOHcCRTSlCS16/768fYjeMmamAM9OTlmuKPFkEne7ylifvquB/jun8OkYl0YXHtEBYB3lq7I3/kyLyJFsCG077aiCz0ZKdVq4Ae0j+LcBM6TRrQf05RA6Sm4L6Tlcb/I/gNshtthY+/7RYWnmkE63ab6FsWgDGDT4CoqI6MpjsISgAvAhAqcqgr8cLaQesqpa+sCQz6BO0t3ZBz2CURQ/gZapHlie+P9wPV5kXyEhXUyqSEgLX4XhOk705ljEwch+qcZgjW5OvnYFGHYJ7HyfMe7L5MnD3uWs8c9B39qC09vctJi/t/D+/ipFwVeV7Ai2fCP9wARmv8TwK2HZA1tcGMkE2BNHCRyE/mXa08a4atvYDl/u/cL3TyLJ76CVIiCu44+Qlr3XT9ne/jNbElqzv1CdxzjgXeQhbEY+wJvXx998yxlcAJpOyD75r91JIRAWmD0sRQKL1KF1/YKe05RE3rZT5S4gPdz5Nk7NAwUqSNYKmHUt/joD+7EmqPYTMDmX4Pa3P1RKU3Ds/ZHgKvAxxbDlIRJugEmL5UkbQW0pieeGcP54v8SO0JXVgV5GxHFY2S9mFdGyHJjoNZr9fUcI8pl6qCHqyxsQ5Es4kLKebt2FY+1BYsbUxYOMAidByj6Wks=
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_373c076bae3a_key -iv $encrypted_373c076bae3a_iv -in bot_deploy_key.enc -out bot_deploy_key -d
- git submodule update --init --recursive
script:
- sudo -E make tex_env
- make all
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then bash ./developers/deploy-ghpages.sh;
  fi
